/**
 * Bundles each surface into a single self-contained HTML file.
 *
 * A sandboxed iframe cannot fetch anything from another origin, so the JavaScript and
 * CSS have to be inlined rather than linked. The output is committed: hosts spawn
 * `node src/stdio.ts` directly and never run an npm script, so a build that has not run
 * is a card that does not exist.
 *
 * Two surfaces now. The card is ours, markup and all. The view is an empty frame that paints
 * whatever HTML the model sent back in its tool result.
 */

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'esbuild';

const here = path.dirname(fileURLToPath(import.meta.url));
const appDir = path.join(here, '..', 'src', 'app');

const surfaces = [
  {
    entry: 'card.ts',
    css: 'card.css',
    out: 'card.html',
    body: `<div class="wrap">
  <h1>Your bookings</h1>
  <div id="list"><div class="empty">Loading…</div></div>
</div>`,
  },
  {
    entry: 'view.ts',
    css: 'view.css',
    out: 'view.html',
    // The frame is fetched before the tool runs, so the surface arrives afterwards over the
    // ui/ channel and view.ts paints it in here.
    body: `<div id="surface"></div>
<div id="hostinfo"></div>`,
  },
];

for (const surface of surfaces) {
  const bundled = await build({
    entryPoints: [path.join(appDir, surface.entry)],
    bundle: true,
    format: 'esm',
    target: 'es2022',
    minify: true,
    write: false,
  });

  const css = await readFile(path.join(appDir, surface.css), 'utf-8');

  const html = `<!--
  Generated by scripts/build-card.mjs. Edit ${surface.entry} and ${surface.css}, then run
  npm run build:card. Do not edit this file.
-->
<style>
${css.trim()}
</style>

${surface.body}

<script type="module">
${bundled.outputFiles[0].text.trim()}
</script>
`;

  await writeFile(path.join(appDir, surface.out), html, 'utf-8');
  console.error(`${surface.out} written, ${Math.round(html.length / 1024)}kB`);
}
