/**
 * Bundles the card into a single self-contained HTML file.
 *
 * A sandboxed iframe cannot fetch anything from another origin, so the JavaScript and
 * CSS have to be inlined rather than linked. The output is committed: hosts spawn
 * `node src/stdio.ts` directly and never run an npm script, so a build that has not run
 * is a card that does not exist.
 */

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'esbuild';

const here = path.dirname(fileURLToPath(import.meta.url));
const appDir = path.join(here, '..', 'src', 'app');

const bundled = await build({
  entryPoints: [path.join(appDir, 'card.ts')],
  bundle: true,
  format: 'esm',
  target: 'es2022',
  minify: true,
  write: false,
});

const script = bundled.outputFiles[0].text;
const css = await readFile(path.join(appDir, 'card.css'), 'utf-8');

const html = `<!--
  Generated by scripts/build-card.mjs. Edit card.ts and card.css, then run
  npm run build:card. Do not edit this file.
-->
<style>
${css.trim()}
</style>

<div class="wrap">
  <h1>Your bookings</h1>
  <div id="list"><div class="empty">Loading…</div></div>
</div>

<script type="module">
${script.trim()}
</script>
`;

await writeFile(path.join(appDir, 'card.html'), html, 'utf-8');
console.error(`card.html written, ${Math.round(html.length / 1024)}kB`);
